language: node_js
node_js:
- '6'
- 6.2.0
- '4'
- 4.4.5
notifications:
  email:
    on_success: change
    on_failure: always
cache:
  directories:
  - node_modules
before_install:
- npm install -g npm@3.8.9
after_script:
- npm run coverage
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
- "./node_modules/.bin/codeclimate-test-reporter < ./coverage/lcov.info"
env:
  global:
  - secure: PrFCiamM7g7SHS5VDMFSNuTByVkHPjkdnKL2sx7TWULIzM2GbnC+6ToPiwWllFyvSOG3uHmnqnfGOVMxVB4ix4Vc2g4zSeTeMVa5CLIn0RrmNHnbuao02kV6TTdjs29pOxaclgWrbl67xUlvNJqjuO/kL/qZriSnnylhfB3WnrhtRQ3cHWttvI4OksHBF/DNhIbRG0tk5ARuGS0iuNvX1M1J4AKCSjII6UX7ax9eoWYxuLV7ZT+5PjWTKTdbRHTMNfdIZaGJMTQVH6snAmJmDS9Cx7UgkDQvRYNka7zmXSwrItyMN2i7kBtJb9AtrhMVWWPveiqEwqh8+M05PhOBvKxqgNoJN6wlQcwaHUQizKutUqdyP4IjAhEySr6uu2AjHb7Lf7vrCHE+AdWFl2euqQkVQOP9+B1Hb58EVDR7LXvg8mIpzkeiXuW67MvQPlDNdYv/TnQ0PXHcms9F6NzADHUoztLamCB426lxFv1DtLQ6Dwlv5vipMgSqzF3Yv0O1IK9JMdPACK0lD+VvQ2v2PjfLR9nzAVq+eYCkgj4Emlchz6FOWqqKW9Akw8oGBTwptXFN8+O34RR1tb/2bbRX+LiXN0C3crfDIMolzgrJTeEgHaaxWGbZtaUxLxFOMi5UKbaTDtPcvEqkZCcgC6e9o3xVd2gTDCEzqiMQ9NdJ9wA=
  - secure: UqyiuuEeBJNNx4let9t+wSVRcPq40UG+fH57Bm6eh8LfBtaHqasuXlUUJ9BLva1CZZwq37UonQJfDKTsN/owXafMfZVQ5Ijg4GObyzeI/Xu04XXg78q+5Bg47vaOP0T0vJXdjE+qHRExUs9ZduiU3SMsF/2QSof67VwA340/0MISo7Dy8s8pK6McUDbuAeGUnYmhBiD67lE3jfb5gOy30VkmRrXHLyZZutDClgKl3bwH9Cx9h8LtRJIi11iptf9+KZjThtKgdyh2qWxYrdeO0jczAJahgsAk8ZOVzF3wIvJDoIKUm4A5tmimzScNxfRMrZ0sjeSadWPnmt+fUzLVxIcKCeRp4l4g57rabZ9IxwCFMyP3NgrF/NM76GUHHkiZLJ4LTqP0vDVeOj3FzCM44TgrhQ68k/VtcG9r85v5Gp03ytc185jz4gKwtrmdmfS5hYmXIgxO0j7HGzg4T1MFYkp+cm9mBHKnlrzdHyEyk7moC8tOQvrasRyToVwfQ7kfwn2Eha+6VpGBhbQVndF+wXQks5Ao7N4nG+ITfjaPKTAqH7ioTKX2pxCkLyprEiQLD08iwoFKn/rCfp7NjUarF3hRVIaj650eJ2/pLb+9uTka2LqJHNmPo4yXU4jle3DSsK5QLdt2bwV9Z0gZpNXxMlwwBARslNAGw0tJ2kj8IpI=
