language: node_js
node_js:
- '8'
- '6'
notifications:
  email:
    on_success: change
    on_failure: always
after_script:
- npm run coverage
- npm run codeclimate
env:
  global:
    secure: xhap6jB5JzeTA1IXHCfBgwvKSlod3m4kVk0I3pldkhqWSxuS69Wx2e/fCwSnO9ZzctOvaJlZbPZJHB3wzum1b0ruH6lRCaxX/cf8zmtewrZ37udapnd+0x+flhZ2/4ZScCN566UcRSUzAyHadB9Lhiml8XaVQJsz3q2gibx+QYjueg9vtRI9nYhneCB0fQqiCNzNjf0jMB1j7P2ZdoWc1AC8k0c/ngefSzSnMzVJdCMKaX/tMoGIxTZdDmHGsdCYr+8/qor46Tk/j8aumU0LoYxidMFU1IRpK3mB3zdyG6aGrdLoqMRd37gYuh6tKGRkGMMaI1H38OfxvERs+amPbva8+ayMrWnxCYLvrM3CYUy4WgidMLvDlOyt/SPUUYkW33UrxLQ1VzY2H26lziTWDByUjeR+myOZ9hfPP1gg2ow2j9QKhyIdd0ShqEAH91y1F2oeNWdUYuFsGOEqJK5uIFLDji6GR6m5OdP6/ifZEp7e8l9BkGKiQVpg3dyUs6pzQn4GyDEx0VQ9Uoskg1XNeAvRRH42mMlvV5Ma6wxyH8bREo1OacoUrWbYFogcm6FohrTpe3JyApt8fTnT+6Q+Mvaqr8pckCvdx1GcZcAGJFha6wA/F+BFcrpHc9SF1u76ya4f1qh3PqmcXtMY0+afqbC+hy3txZlohpISOnY38JE=
