language: node_js
node_js:
- '8'
- '6'
notifications:
  email:
    on_success: change
    on_failure: always
before_install:
- npm install -g greenkeeper-lockfile@1
before_script:
- greenkeeper-lockfile-update
after_script:
- greenkeeper-lockfile-upload
- npm run coverage
- npm run codeclimate
env:
  global:
  - secure: xhap6jB5JzeTA1IXHCfBgwvKSlod3m4kVk0I3pldkhqWSxuS69Wx2e/fCwSnO9ZzctOvaJlZbPZJHB3wzum1b0ruH6lRCaxX/cf8zmtewrZ37udapnd+0x+flhZ2/4ZScCN566UcRSUzAyHadB9Lhiml8XaVQJsz3q2gibx+QYjueg9vtRI9nYhneCB0fQqiCNzNjf0jMB1j7P2ZdoWc1AC8k0c/ngefSzSnMzVJdCMKaX/tMoGIxTZdDmHGsdCYr+8/qor46Tk/j8aumU0LoYxidMFU1IRpK3mB3zdyG6aGrdLoqMRd37gYuh6tKGRkGMMaI1H38OfxvERs+amPbva8+ayMrWnxCYLvrM3CYUy4WgidMLvDlOyt/SPUUYkW33UrxLQ1VzY2H26lziTWDByUjeR+myOZ9hfPP1gg2ow2j9QKhyIdd0ShqEAH91y1F2oeNWdUYuFsGOEqJK5uIFLDji6GR6m5OdP6/ifZEp7e8l9BkGKiQVpg3dyUs6pzQn4GyDEx0VQ9Uoskg1XNeAvRRH42mMlvV5Ma6wxyH8bREo1OacoUrWbYFogcm6FohrTpe3JyApt8fTnT+6Q+Mvaqr8pckCvdx1GcZcAGJFha6wA/F+BFcrpHc9SF1u76ya4f1qh3PqmcXtMY0+afqbC+hy3txZlohpISOnY38JE=
  - secure: KhXJBh0sKbR1vxEZrRQSbonMvU75iUaKnF7sK6y07joKQLss8turJYsrNvvEnm+AHtNilaHAxYdabneQSzvBWwgNXRLueFGXFC2jMP6v6haU5j0fboABwZCdbbkuzea+Gic8HzoxVHi4jXll28Fpe/b4vT6saZoy5WwgPj6avGNgELgwK1iqiTiLDLRtUxtYsQFl8PxxuXGTBaObat8WRoff+3gZuOHKxHBxRrX5hJ9grRIGq0zPQZFNmwkkvj4h9Uzlq6QgQ90zFuxT/ClAiPb8M+MkK9uFMWynFVDKMBflg2yIqfU5+U0WG+bYwlgVH1eFDFc37WQdVik/kNDEYev1EDr9DzznuJUOCbKwUGC9iyDPpmfGnA65CkweFpx39+afFPQMvQ1ZApyjrN/ywYW4l/+/maAa++wmAduXIVyyBKCPMk8rcs1hisAutJuJbrC1uS7hyPtzSZOn70tVVwZzw81ZR4RC0JVs22bJeu5/qIW03E9aMOw1E06HJ6BNCgPPYVxO+n2yLwhrATgrBeMiqyICthdc735wHXGRVqq4CWXFozs67TOoBnELZRRWUGjEDwo2d+PRoYwTz6DC0bj2OqZ0XFtILM0kgl+cQUZ19wlcQ+TKxAxwQ0HrEOvYAC4/EQXJufqjm+t1zzycYCKIdcm81l7sAB0LlhD6wsA=
