language: node_js
node_js:
- '6'
- 6.2.0
- '4'
- 4.4.5
notifications:
  email:
    on_success: change
    on_failure: always
cache:
  directories:
  - node_modules
before_install:
- npm install -g npm@3.8.9
after_script:
- npm run coverage
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
- "./node_modules/.bin/codeclimate-test-reporter < ./coverage/lcov.info"
- snyk auth $SNYK_TOKEN && snyk monitor
env:
  global:
  - secure: ohtn0uqJOk1C5rBvHBNNHm6RiSRiYsLDsc868mjBszi1/bj6xSVJyhJ6Y6xS2uvqM+7v/YO20j5iR4rSHDjsfh1L5nGLgByYrZXIymfd2yzWIiMrpVkT5XmgiGNDa0QDKm6H0x68A8bDnm8Qz7YCXui77Ou/jKtRxtbGPRFrSInedXcaFtExDKF566JxbNmu6tlkgAdwfAPxwoJuVvyDPbGxFjw96qgMcze/84fGGexxrrUO9gkdaCZ/HkwAw4v7xBUNMflDCBWNPrVyJJNAr+PHW1E3CqsxUUsT0aTf3Cu1/mJRxs2dH5ejD28StFCGMRWbOjiZ7zkYy85G7kLsNsuDmDin1Wr11PcRiw5YbDKTANfb/UVoVYOY0Xyy2fHU4Vw8AtnrDQML6HRNe86za6lHhDFYHdMSy3biswFmyk+ZR1pbXZU5MHMfAxumeXHxswHdakKdAwF8Z97d+0E2x/U5JbFovFNT5jrS914O0IZDgmFeeoCzpbLDXQhqiRgn4M5ZUWpQTRhGVCfc+FT8ks02eA43Em/PLvB1oGNip1WMAjdC4jFzvD7WqI9mL70rCYwyiu0nu4ZIQAMagM6ZxSz5PpjIrF1KOhUovDf6EUgWpFdNExZdNqfJXj0wogvVW+vOkllWj/lI0QzwrPIQO33IX2p1rxvOL5h7StKZWr4=
  - secure: 0pxa9eU8vPxyVVgD4blySVpuypZbitvN5BHCvOkTSDVv6KssAbMVyJ6qtlXwrVqNZ/WKcRxOjTR18dyVYR3kUG673dTl1LHf8oeGgcmABELOi7SyeIGMRI9Xt9cuJ0SnE5C6FhTVaviQYtcZh7r6u4VLIoPKy0Xdi+AHcEAre+dml7er8vxvS2COcSrOtK+q9w1I3Pci/WSFvindAepRTSJigMXBcsBT12C7qj9Lq/WEq4cIJR2TeNTJON/KkLHPNQD3Yu87hZRODcn//Gaw/Wz/CQoLLDjay0E4KC4eXOLntzW8HeSHmEjtkE6y6254jBpKT3NUTeHgLj+pAcLTf07ngWpEMAjGiZcwZ2/+REjC2CvYzeilpMb4aNacQRqhbLR8qRLU9le9KsBG4OhIeQmvdvHZVwb7hnT6zENb0pgBv4Uuar3ZdwPuOkniJWa9N5N6aY76LUS2q3HOMqkE05D+mAzl4CDB/vd1VY5wE7AivIn3qL+Wkp5DjGe6dRw8uXd8ZEJEZMZyF7XV6PdXUa+VIRd1w5ZZF6PWsnmZ+cn4gWyXFNUG/PjrFEWSqOOW4RYahkujw62koP4ABe71qqBa1CJMEmrJa0u0XBebVut5n1QcNvqTgUqAPSgyqHD0gs5GXi7NMG6ZlxX7I0ubpW2eGoPRDJKQcbiUU/paNy8=
  - secure: fEKz4jtIYZ0Crrwt7P7uvclTdZNedMl+rErSmetjiaerEpeNHuZeQNlLoCw5IgxqDjZ/AfTEgsGPA05ZE6F5QGF91BjAQkyOUyatzeYCkmaSpea4VCdp2rZsMM16zM8+6ZnxjqtNj5fpBji4P7JKbyTYKZRwQ3sovAaY1YPDkmerCoRe9cvMMrgCAG5qzSnUnWDnTRpWq/ZL7vwP7qNUE5OAvRrnm5j0SEG53ViWLCGeGqjztU5781ovyXheFMnePSCzJBBOTv8xoSWeaYtm4mPC0k65LAkym/K/xuTeexRyDeOdUgVA2EnYvUPgndm5cCbOi1OtBwBmn17XpB12hyJFcWBEWSybnETJXzUoUS62u5t4z/1BWH29C6maiVmNRH18nRbw6CJTSH+8eWPY+7sTwxqd1tIkb+hO1ms0e8B7SUn2z4Im87EoQ5Gs0JLKzefJ6sfJSpyEql90g67exNampNcoezBhWCh0HUw7Wi/UMmszA2EpLgXeT7Qbmq91azL2CVnUOYjIEb8/m+EladCB4sPtVDy0zgQ/2iFoXW0hKIpdsNVeUXs6/OnWqDMUCDEffhMBNjUzPLw49z3A/lrUWw+Iw9p18YoowDDy/3yqPOLcWaBBPxpJTBTCF7fcbG8EXOhmuMaWgJDdDaDN8EGvYwlDKzxx/CNKopiidAk=
