language: node_js
node_js:
- '8'
- '6'
notifications:
  email:
    on_success: change
    on_failure: always
before_install:
- npm install -g greenkeeper-lockfile@1
before_script:
- greenkeeper-lockfile-update
after_script:
- greenkeeper-lockfile-upload
- npm run coverage
- codecov
env:
  global:
  - secure: KhXJBh0sKbR1vxEZrRQSbonMvU75iUaKnF7sK6y07joKQLss8turJYsrNvvEnm+AHtNilaHAxYdabneQSzvBWwgNXRLueFGXFC2jMP6v6haU5j0fboABwZCdbbkuzea+Gic8HzoxVHi4jXll28Fpe/b4vT6saZoy5WwgPj6avGNgELgwK1iqiTiLDLRtUxtYsQFl8PxxuXGTBaObat8WRoff+3gZuOHKxHBxRrX5hJ9grRIGq0zPQZFNmwkkvj4h9Uzlq6QgQ90zFuxT/ClAiPb8M+MkK9uFMWynFVDKMBflg2yIqfU5+U0WG+bYwlgVH1eFDFc37WQdVik/kNDEYev1EDr9DzznuJUOCbKwUGC9iyDPpmfGnA65CkweFpx39+afFPQMvQ1ZApyjrN/ywYW4l/+/maAa++wmAduXIVyyBKCPMk8rcs1hisAutJuJbrC1uS7hyPtzSZOn70tVVwZzw81ZR4RC0JVs22bJeu5/qIW03E9aMOw1E06HJ6BNCgPPYVxO+n2yLwhrATgrBeMiqyICthdc735wHXGRVqq4CWXFozs67TOoBnELZRRWUGjEDwo2d+PRoYwTz6DC0bj2OqZ0XFtILM0kgl+cQUZ19wlcQ+TKxAxwQ0HrEOvYAC4/EQXJufqjm+t1zzycYCKIdcm81l7sAB0LlhD6wsA=
